### ISSUE TITLE
technical report google doc

### ISSUE THREAD

**Issue by SiRumCz** [SiRumCz/CSC501#60]
https://docs.google.com/document/d/1cOXpbT2oeezq340b_Pp8ggQVJ8FkOUZSuJ1loz5uF9c/edit?usp=sharing

**Comment by soroushysfi** [comment]
> https://docs.google.com/document/d/1cOXpbT2oeezq340b_Pp8ggQVJ8FkOUZSuJ1loz5uF9c/edit?usp=sharing

Documentation was pretty good! thanks.
