### ISSUE TITLE
getting py2neo running 

### ISSUE THREAD

**Issue by noonespecial009** [SiRumCz/CSC501#68]
Soroush, have you been able to get py2neo to work? Kevin, would you be able to help you him out? There is the official Neo4j Python driver: https://neo4j.com/developer/python/ 

Other options might be:
Get Docker Compose to work with both neo4j and python container
Use a virtual machine
Uninstall Python and reinstall
Use a virtual environment

**Comment by soroushysfi** [comment]
Thanks! I was able to fix it. The problem was with python3. I had to update it and after I executed it worked.

**Comment by noonespecial009** [comment]
Nice!

**Comment by noonespecial009** [comment]
I'm trying to make links between all of he nodes but I am running low on memory. It worked last night when I increased the memory in Docker but today not working.

**Comment by noonespecial009** [comment]
fixed it
